### ISSUE TITLE
High CPU usage when speedtest.

### ISSUE THREAD

**Issue by butinhi** [immortalwrt/immortalwrt#1029]
Pls help me how to fix this problem. I test speed or download something with very high CPU usage

<a href="https://ibb.co/FgxmTYw"><img src="https://i.ibb.co/FgxmTYw/A-nh-chu-p-ma-n-hi-nh-2023-08-06-220705.png" alt="A-nh-chu-p-ma-n-hi-nh-2023-08-06-220705" border="0"></a>

**Comment by butinhi** [comment]
> does this problem occur on a wired or wireless network? is hardware offload enabled in `network/firewall`?

I turned on it but not effect

**Comment by cherinyy** [comment]
It seems that you are using the SNAPSHOT version of the firmware, I'm not sure about this. Can you try the [23.05-SNAPSHOT](https://downloads.immortalwrt.org/releases/23.05-SNAPSHOT/targets/mediatek/mt7622/immortalwrt-23.05-snapshot-r26857-f853776af6-mediatek-mt7622-xiaomi_redmi-router-ax6s-squashfs-factory.bin)  version please?

**Comment by cherinyy** [comment]
> You used this version and not got problem with CPU usage?

I don't have an AX6S so my situation may not apply to you. But I have no problem with my JCG Q30 PRO, which is on the MT7981 platform.

**Comment by butinhi** [comment]
> > You used this version and not got problem with CPU usage?
> 
> I don't have an AX6S so my situation may not apply to you. But I have no problem with my JCG Q30 PRO, which is on the MT7981 platform.
Maybe problem with mt7622 (ax6s)

**Comment by 1715173329** [comment]
I guess this is a upstream issue. Anyway mt7622 is a deprecated platform, just sell it and buy mt7981.

This branch has the best mt7622 support btw.
https://github.com/padavanonly/immortalwrtARM/tree/mt7622

**Comment by butinhi** [comment]
> I guess this is a upstream issue. Anyway mt7622 is a deprecated platform, just sell it and buy mt7981.
> 
> This branch has the best mt7622 support btw. https://github.com/padavanonly/immortalwrtARM/tree/mt7622

I am using from this source. It's good for mt7622 but it's old and not updated

**Comment by olimpiumarius** [comment]
@This problem is from the speed test software that is from the Microsoft Store, the problem must be sent to this program, whatever router you use does this, I use wrt1900acs v2 with ddwr and openwrt does the same!

**Comment by butinhi** [comment]
> @this problem is from the speed test software that is from the Microsoft Store, the problem must be sent to this program, whatever router you use does this, I use wrt1900acs v2 with ddwrt and openwrt does the same!

Same problem with download something from internet

**Comment by cherinyy** [comment]
This is the hardware offload not taking effect, you need to find available firmware.

**Comment by butinhi** [comment]
> This is the hardware offload not taking effect, you need to find available firmware.

I changed to lede openwrt which has turboacc with MTK WED WO offloading option. It solved my problem. I hope immortalwrt will have it on future
![Uploading Screenshot_2023-08-15-06-29-17-629_com.android.chrome.jpg…]()

**Comment by cherinyy** [comment]
> I hope immortalwrt will have it on future

You may need to [report this issue upstream](https://github.com/openwrt/openwrt/issues/new?assignees=&labels=bug&projects=&template=bug-report.yml), we don't have the same equipment to test with.

**Comment by shown19** [comment]
Hi guys, I know this is not related to the main issue, but just wondering if is it possible to bridge the WIFI to a VLAN instead of a default br-lan? Let see I have created a vlan22, and I want it to be used by the WIFI. Is it possible? I tried on my part but it's not working. 

`
config device
option name 'br-lan'
option type 'bridge'
list ports 'lan1'
list ports 'lan2'
list ports 'lan3'
list ports 'lan4'
list ports 'ra0' <-------- Here's my 2.4ghz WIFI
list ports 'rai0'

config interface 'lan'
option proto 'static'
option netmask '255.255.255.0'
option ip6assign '60'
option device 'br-lan.1'
option ipaddr '192.168.100.1'

config bridge-vlan
option device 'br-lan'
option vlan '1'
list ports 'lan1'
list ports 'lan4'

config bridge-vlan
option device 'br-lan'
option vlan '22'
list ports 'lan1:t'
list ports 'lan2'
list ports 'lan3'
list ports 'ra0' <--------  in hope it will work but it didn't
`
