### ISSUE TITLE
Package default-settings with wrong depends

### ISSUE THREAD

**Issue by abu9** [immortalwrt/immortalwrt#1350]
### Describe the bug

default-settings&(chn) now is `DEPENDS:=+luci` but the fact that it's not revellent to `luci` but `uci` to modify setting, it could cause unnecessary pkg depends selects  with luci and luci-light while using Nginx frontend. 

### ImmortalWrt version

all

### ImmortalWrt release

n/a

### ImmortalWrt target/subtarget

n/a

### Device

n/a

### Image kind

Official downloaded image

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by 1715173329** [comment]
It's by design as a meta package, and `luci` uci configuration is provided by `luci` package.
I would say the nginx version is not well maintained and sometimes may lead unexpected issues, so it's not considered.

Anyway, this package is not important, if you prefer using nginx as frontend, just ignore it.
